#!/bin/bash

# Use the directory of this script as the base path for
# the other executables
base=${0%/*}
ms=master_server
server=server.js
slaves="--slaves $base/slaves"

do_start()
{
        pid=`pgrep -f $server`
        if [ $pid ]; then
           printf  "$server already running ($pid)\n"
        else
            printf "starting $server\n"
            $base/js/$server 2>&1 >> $base/server.js.log &
        fi
        pid=`pgrep $ms`
        if [ "$pid" ]; then
            printf "$ms already running ($pid)\n"
        else
            printf "starting $ms\n"
            $base/$ms --port 9321 $slaves -d 8  2>&1 >>$base/master_server.log &
        fi
}

do_stop()
{
        pid=`pgrep -f $server`
        if [ "$pid" ]; then
            printf  "killing $server ($pid)\n"
           pkill -f $server
        fi
        pid=`pgrep -f $ms`
        if [ "$pid" ]; then
            printf  "killing $ms ($pid)\n"
            pkill -f $ms
        fi
}

do_status()
{
        pid=`pgrep -f $server`
        if [ "$pid" ]; then
            printf  "$server running ($pid)\n"
        else
            printf  "$server not found\n"
        fi
        pid=`pgrep -f $ms`
        if [ "$pid" ]; then
            printf  "$ms running ($pid)\n"
        else
            printf  "$ms not found\n"
        fi
}

case "$1" in
    start) do_start;;
    stop) do_stop;;
    status) do_status;;
    restart) do_stop; do_start;;
  *)
	echo "Usage: bling {start|stop|status|restart}" >&2
	exit 3
	;;
esac
