CPPFLAGS+=-std=c++0x
ALL_BIN=master_main spi-time tx-test rx-test


all: $(ALL_BIN)

clean:
	-rm -f $(ALL_BIN) *.o


spi-time: LDLIBS+=-lbcm2835
spi-time: spi-time.cpp

rx-test: LDLIBS+=-lbcm2835 -lstdc++
rx-test: rx-test.o rt_utils.o nrf24l01.o messages.o

tx-test: LDLIBS+=-lbcm2835 -lstdc++
tx-test: tx-test.o rt_utils.o nrf24l01.o messages.o


master_main: LDLIBS+=-lbcm2835 -lstdc++ -lncurses
master_main: master_main.o rt_utils.o nrf24l01.o messages.o